# fly.toml app configuration file generated for fitlogic-backend on 2023-04-24T10:54:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fitlogic-backend"
primary_region = "atl"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
